feat: 會員中心個人資料切版
TripPlus-003/TripPlus-client pull request #10
Opened 2023-05-09 07:29 UTC by happy9990929

2023-05-09 13:58 UTC, gn00678465 requested changes

2023-05-09 14:10 UTC, happy9990929 commented on src/pages/user/account.tsx
> +              <Box className="w-full md:w-2/5">
form 在第 67 行

2023-05-10 12:43 UTC, gn00678465 approved these changes

2023-05-11 00:49 UTC, gn00678465 requested changes

2023-05-11 00:49 UTC, gn00678465 commented on src/pages/user/account.tsx
>                  <FormControl my={10}>
必填可以加入 isRequired 屬性

2023-05-11 11:41 UTC, gn00678465 approved these changes

2023-05-12 01:23 UTC, yuhantaiwan approved these changes

2023-05-12 01:24 UTC, merged