feat: 會員中心追蹤專案切版
TripPlus-003/TripPlus-client pull request #20
Opened 2023-05-20 03:46 UTC by happy9990929

2023-05-20 12:53 UTC, gn00678465 requested changes

2023-05-20 12:53 UTC, gn00678465 commented on src/pages/user/followings.tsx
> +      id: 0,
假資料重複的 key

2023-05-20 12:53 UTC, gn00678465 commented on src/pages/user/followings.tsx
> +                      ${item.price}
可以參考後台的 utils currency function

2023-05-20 12:53 UTC, gn00678465 commented on src/pages/user/followings.tsx
> +                <Box
卡片可以考慮做成一個 reusable 的 component

2023-05-21 07:00 UTC, yuhantaiwan requested changes

2023-05-21 09:41 UTC, yuhantaiwan approved these changes

2023-05-22 21:39 UTC, gn00678465 approved these changes

2023-05-22 21:39 UTC, merged