feat: 調整個人資料頁面圖片顯示方式
TripPlus-003/TripPlus-client pull request #22
Opened 2023-05-20 12:34 UTC by gn00678465

2023-05-20 13:50 UTC, happy9990929 requested changes

2023-05-20 13:50 UTC, happy9990929 commented on src/pages/user/account.tsx
>  import Image from 'next/image';
Image 已放進 component，可以移除

2023-05-21 03:04 UTC, happy9990929 approved these changes

2023-05-21 09:44 UTC, yuhantaiwan approved these changes
great

2023-05-21 09:44 UTC, merged