feat: 首頁切版
TripPlus-003/TripPlus-client pull request #23
Opened 2023-05-20 15:54 UTC by yuhantaiwan

feat: 首頁切版
完成桌機版，手機版待修改

2023-05-26 00:26 UTC, gn00678465 requested changes

2023-05-26 00:26 UTC, gn00678465 commented on src/pages/index.tsx
> +                  ></Image>
svg 相關檔案設定可以加上
```
style={{
    width: 'auto',
    height: 'auto'
  }}
```
消除警告

2023-05-26 00:26 UTC, gn00678465 commented on src/pages/index.tsx
> +                        className="aspect-ratio-object rounded-lg"
缺少了 priority 屬性

2023-05-26 09:34 UTC, happy9990929 requested changes

2023-05-26 09:34 UTC, happy9990929 commented on src/components/Swiper/cases.tsx
> +                          </Text>
左邊的金額太長會被換行
已結束加上 whiteSpace={'nowrap'}

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +      <Box className="flex flex-col items-center justify-center">
加上 title 
如
<Head>
   <title>Fund Your Next Adventure-TripPlus+</title>
</Head>

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +              </Link>
選單可加上 hover 效果，
如 hover:text-gray-500

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +            </Link>
{'>'} 可用 icon MdChevronRight

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +            </Link>
{'>'} 可用 icon MdChevronRight

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +            </Link>
{'>'} 可用 icon MdChevronRight

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +      >
因主要圖片在下方，手機板背景可設定 bg-[center_bottom] md:bg-center
手機板高度看起來有點長，設計稿我要提案的按鈕位置比較靠近下方的主圖

2023-05-26 09:34 UTC, happy9990929 commented on src/pages/index.tsx
> +                <span className="mr-2 text-[36px] md:text-[54px]">
將手機板尺寸固定直式排版，
可設定 flex-col md:flex-row

2023-05-26 09:36 UTC, happy9990929 commented on src/pages/index.tsx
> +      <Box className="flex flex-col items-center justify-center">
<Head>
   <title>Fund Your Next Adventure-TripPlus+</title>
</Head>

2023-05-27 08:56 UTC, happy9990929 approved these changes
Good job

2023-05-27 09:16 UTC, gn00678465 approved these changes
Good job

2023-05-27 09:16 UTC, merged