feat: 專案內容切版
TripPlus-003/TripPlus-client pull request #27
Opened 2023-05-30 20:57 UTC by gn00678465

2023-05-31 17:47 UTC, happy9990929 requested changes

2023-05-31 17:47 UTC, happy9990929 commented on src/components/Swiper/Carousel/index.tsx
> +        />
1296~1480會出現橫向卷軸，可改2xl再顯示
display={{ base: 'none', '2xl': 'block' }}

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +      <Container px={{ base: 3, xl: 0 }} maxW="1296px">
可寫成變數
maxW={'container.xl'}

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +              ></Progress>
進度條設計稿高為 6px

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +              </Button>
MdBookmarkBorder Icon 電腦版 24px，手機版 20px

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +    />
按鈕可加個 hover 效果
_hover={{ bgColor: 'white' }}

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +                </li>
提案者、統一編號的值需對齊

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +    >
手機版需置中，可加上 mx={'auto'}

2023-05-31 17:47 UTC, happy9990929 commented on src/pages/project/[id]/index.tsx
> +      >
加上 Head
```
<Head>
  <title>
    「跟著手語去旅行」| 讓聾人打造一個專屬於聾人團員的遊程活動！-TripPlus+
  </title>
</Head>
```

2023-05-31 21:12 UTC, gn00678465 commented on src/pages/project/[id]/index.tsx
> +      <Container px={{ base: 3, xl: 0 }} maxW="1296px">
container.xl 寬度為 1280
設計稿的寬度為 1296

2023-06-01 05:12 UTC, gn00678465 commented on src/pages/project/[id]/index.tsx
> +      <Container px={{ base: 3, xl: 0 }} maxW="1296px">
已調整 Chakra-UI 設定

2023-06-01 05:43 UTC, gn00678465 commented on src/pages/project/[id]/index.tsx
> +                  {currencyTWD(328300)}
在 utils 建立 replaceTWDSymbol function 處理 $ 符號

2023-06-01 05:53 UTC, yuhantaiwan commented
Great

2023-06-01 05:54 UTC, yuhantaiwan approved these changes

2023-06-01 11:40 UTC, happy9990929 approved these changes
Great!

2023-06-01 11:40 UTC, merged