付款頁面切版
TripPlus-003/TripPlus-client pull request #29
Opened 2023-05-31 18:04 UTC by yuhantaiwan

2023-05-31 22:05 UTC, gn00678465 requested changes

2023-05-31 22:05 UTC, gn00678465 commented on src/pages/checkout/index.tsx
手機板畫面輸入框被擠壓到非常小

2023-06-01 00:22 UTC, yuhantaiwan commented on src/pages/checkout/index.tsx
> +                  <span>選擇數量</span>
下方的 `NumberInput` 已有設 `defaultValue={1}`

2023-06-01 00:23 UTC, yuhantaiwan commented on src/pages/checkout/index.tsx
> +                    <span>額外贊助</span>
下方的 `NumberInput` 已有設 `extraMoney = '0'`

2023-06-01 12:32 UTC, happy9990929 requested changes

2023-06-01 12:32 UTC, happy9990929 commented on src/pages/checkout/index.tsx
> +              />
進度條高度 6px
h={'6px'}

2023-06-02 07:27 UTC, gn00678465 requested changes
執行 server 並進入此頁面會出現 "prop href did not match. server client next" 錯誤
可以加上 `getStaticProps` or `getServerSideProps` 轉換成 SSG 或者是 SSR 頁面

2023-06-02 07:53 UTC, gn00678465 approved these changes
Good job

2023-06-02 12:03 UTC, happy9990929 approved these changes
good!

2023-06-02 12:03 UTC, merged