feat: 列表頁調整成SSR
TripPlus-003/TripPlus-client pull request #33
Opened 2023-06-06 18:09 UTC by happy9990929

2023-06-07 01:15 UTC, gn00678465 requested changes

2023-06-07 01:15 UTC, gn00678465 commented on src/components/ProList/index.tsx
> +    [`/api/projects?page=${page.page}`, queryParams],
與
`[unstable_serialize(['/api/projects', paramsQuery])]` 不相同造成預設資料沒有寫入
可以將 `if (isLoading) return <Loading />` 註解看看結果

2023-06-08 05:28 UTC, gn00678465 approved these changes
Good job

2023-06-08 05:29 UTC, gn00678465 commented on src/components/ProList/index.tsx
> +    [`/api/projects?page=${page.page}`, queryParams],
主要是
/api/projects?page=${page.page}
與
'/api/projects
兩者不同

變數名稱其實沒有差別，因為都會被轉換成 string

2023-06-10 03:55 UTC, yuhantaiwan approved these changes
Great

2023-06-10 03:55 UTC, merged