Feature/member_register
TripPlus-003/TripPlus-client pull request #7
Opened 2023-04-30 13:37 UTC by happy9990929

2023-05-02 21:37 UTC, gn00678465 approved these changes

2023-05-03 13:29 UTC, yuhantaiwan requested changes

2023-05-03 13:29 UTC, yuhantaiwan commented on .env.production
> +BASE_API_URL=https://trip-plus-server-dev.zeabur.app
production 環境的 api 網址是 https://trip-plus-server.zeabur.app/
development 才會加上 .dev。所以 .env.development  的 BASE_API_URL 是 https://trip-plus-server-dev.zeabur.app/

2023-05-03 13:39 UTC, yuhantaiwan approved these changes

2023-05-03 13:46 UTC, merged