Feature/member_login_api
TripPlus-003/TripPlus-client pull request #9
Opened 2023-05-07 13:55 UTC by happy9990929

2023-05-07 14:59 UTC, gn00678465 requested changes

2023-05-07 14:59 UTC, gn00678465 commented on src/components/Layout/header.tsx
> +    localStg.clear();
登出後應該只需要清除 userInfo 就好，localStorage 可能會有其他的資料
localStg.remove('userInfo')

2023-05-07 14:59 UTC, gn00678465 commented on src/pages/signup/index.tsx
已登入的狀態下， /signup 的頁面需要導向到首頁嗎

2023-05-08 08:39 UTC, yuhantaiwan approved these changes
good

2023-05-08 12:14 UTC, gn00678465 approved these changes

2023-05-08 12:16 UTC, gn00678465 approved these changes
zustand 研究會進一步使用後
可以將 authStore 把 userInfo 的資料存進去並持久化
可以使用 get 的方式去判斷 token 是否存在當作是否已經登入的依據

2023-05-08 12:47 UTC, merged